### PR TITLE
Switch CELoss to BCEWithLogitsLoss

### PR DESCRIPTION
**Pull request by AgaMiko**
Training with BCEWithLogitsLoss results in more stable loss values. BCEWithLogitsLoss is better suite for our problem.

### CODE REVIEW

**Review by alicjak1519 — APPROVED** [review]
Maybe we can parametrize loss function? Or is it unnecessary?

**Review by MilenaOlech — APPROVED** [review]

**Comment by AgaMiko** [comment]
> Maybe we can parametrize loss function? Or is it unnecessary?

Sure, I wanted to do it at first, but in the end, BCEWithLogitsLoss seems to be better. We already have too many parameters so I thought leaving just one parameter like now, would be better. Of course, If you find it necessary I can add it, it's a small change :)
Let me know what you think @majsylw @alicjak1519.

**Comment by alicjak1519** [comment]
@AgaMiko You are right, if this loss function is better, its parameterization could be redundant. ;)

**Comment by majsylw** [comment]
@AgaMiko you mentioned also that it can be sensitive to data, as we will add next week additional greeak dataset and also additional head with distances I will put this as argument with default BCE

**Comment by AgaMiko** [comment]
Okay, I added a  parameter but only to the model itself with a default value set to BCELoss. Later on, it can be added to the config, if needed.

**Review by majsylw — APPROVED** [review]

**Pull request merged**
